// Code generated by hertz generator.

package main

import (
	"context"
	"sync"

	"github.com/cloudwego/hertz/pkg/app/server"
	"pdm-plugin.github.com/biz/dao"
	"pdm-plugin.github.com/config"
	"pdm-plugin.github.com/logs"
	"pdm-plugin.github.com/utils"
)

func main() {
	logs.Init()

	logs.CtxInfo(context.Background(), "123")

	config.Init("./conf/conf.yaml")
	dao.Init()
	utils.GlobalLock = sync.Mutex{}

	h := server.Default()

	register(h)
	h.Spin()
}
