// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"pdm-plugin.github.com/biz/dao"
	"pdm-plugin.github.com/config"
	"pdm-plugin.github.com/logs"
)

func main() {
	logs.Init()

	config.Init("./conf/conf.yaml")
	dao.Init()

	h := server.Default()

	register(h)
	h.Spin()
}
